// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Models;

#nullable disable

namespace ServerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103195507_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerApp.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Author = "Сунь-Цзи",
                            Status = "Available",
                            Title = "Мистецтво війни"
                        },
                        new
                        {
                            ID = 2,
                            Author = "Тарас Шевченко",
                            Status = "Borrowed",
                            Title = "Кобзар"
                        },
                        new
                        {
                            ID = 3,
                            Author = "Джордж Орвелл",
                            Status = "Available",
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("ServerApp.Models.BorrowRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("LibrarianID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.HasIndex("LibrarianID");

                    b.ToTable("BorrowRequests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BookID = 2,
                            LibrarianID = 1,
                            RequestDate = new DateTime(2025, 11, 3, 21, 55, 7, 305, DateTimeKind.Local).AddTicks(6918),
                            Status = "Approved"
                        },
                        new
                        {
                            ID = 2,
                            BookID = 3,
                            LibrarianID = 2,
                            RequestDate = new DateTime(2025, 11, 3, 21, 55, 7, 308, DateTimeKind.Local).AddTicks(1976),
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ServerApp.Models.Librarian", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "olena.koval@library.com",
                            Name = "Олена Коваль",
                            PasswordHash = "hash123"
                        },
                        new
                        {
                            ID = 2,
                            Email = "ihor.petrenko@library.com",
                            Name = "Ігор Петренко",
                            PasswordHash = "hash456"
                        });
                });

            modelBuilder.Entity("ServerApp.Models.BorrowRequest", b =>
                {
                    b.HasOne("ServerApp.Models.Book", "Book")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerApp.Models.Librarian", "Librarian")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("LibrarianID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("ServerApp.Models.Book", b =>
                {
                    b.Navigation("BorrowRequests");
                });

            modelBuilder.Entity("ServerApp.Models.Librarian", b =>
                {
                    b.Navigation("BorrowRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
